apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mnuttall/simple
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
